require('lua_modules.settings')
require('lua_modules.keymaps')
require('lua_modules.plugins')
require('lua_modules.colorscheme')
require('lualine').setup()
require('lua_modules.nvim-tree')
require('lua_modules.treesitter')
require('lua_modules.lspconf')
